### ISSUE TITLE
Allow removal of non-current Sessions

### ISSUE THREAD

**Issue by brynwhyman** [kinglozzer/silverstripe-session-manager#13] opened 2021-02-02 01:29 UTC
### Overview
This covers the CMS action to log out of non-current sessions.

### Acceptance Criteria
- [x]  Create API endpoint on SessionManagerField to remove sessions
- [x]  Add Log out action to non-current sessions as per [designs](https://www.notion.so/Session-Management-UI-Tasks-dee403ae79664f35b5f6d0e8a4a94393)
- [x] The session details for a device is removed when the log out action happens
- [x] The UI shows a ‘progression of change’ so the user understands a change has been made, i.e loading indicator/ update the state the ‘log out’ button to ‘logging out’ (TBC)
- [x] A toast notification is presented to confirm the successful action
- [x] Server failures are handled in the UI
- [x] The display of other devices is reordered when one is removed. I.e. those below it are shifted up

### Notes
- > Server failures are handled in the UI 
  - A toast notification should suffice for most things. We can probably more gracefully handle the scenario where a user's current session has ended = prompt them with the login modal. 
  
### PRs
- [x] https://github.com/silverstripe/silverstripe-session-manager/pull/39

**Comment by emteknetnz** [comment] 2021-03-11 22:01
Fiarly significant issue to solve where reverting a session also logs out the current session:

Replication steps:
1. Login as an admin using firefox (primary browser)
2. Login as the same admin using chrome ("rogue login" browser)
3. Using firefox, revoke the chrome session
4. Refresh chome - now logged out - good
5. Refresh firefox - now logged out - bad

I got the same issue using the ui-rendering branch with the new UI, as well as the last commit Loz made with the old UI - 65dd641

The value of `RememberLoginHash::config()->get('logout_across_devices')` called in `SilverStripe\SessionManager\Security\LogOutAuthenticationHandler` is `true`

Likely it's related to this existing bug
https://github.com/silverstripe/silverstripe-framework/issues/9794

Possibly also related
https://github.com/silverstripe/silverstripe-framework/issues/8345

**Comment by emteknetnz** [comment] 2021-03-11 22:35
Have confirmed that change the config value of `RememberLoginHash.logout_across_devices` from `true` to `false` fixes this behaviour

At first it seems like a good solution here would be to update the session-manager remove endpoint to temporarily force the config value to 'false', perform the  then revert it back to whatever it was beforehand

However I tried this and it does not work

A very weird thing happens after you revoke the chrome session and refresh chrome, it will hit this bit of code 
https://github.com/silverstripe/silverstripe-session-manager/blob/1/src/Security/LogOutAuthenticationHandler.php#L45

Which I wouldn't expect because chrome is supposed to already be logged out?

Hitting this code then logs out firefox

We *could* update the code above to instead not check for the value of `logout_across_devices`, but, I'm more concerned about why this is getting hit at all by chrome.  It's like it's still not 100% logged out after firefox revoked its session?

**Comment by emteknetnz** [comment] 2021-03-14 21:41
OK, it's not really concerning, they flow is:

Firefox - revoke session
Chrome - refresh
- LoginSessionMiddleware::process():33
- RequestAuthenticationHandler::logout():83
- CookieAuthenticationHandler::logout():251
- RememberLoginHash::clear():183 ($alcDevice = null)

All that's happening is the RememberLoginHash is being cleared almost as a clean up task after the login session was previously cleared

**Comment by emteknetnz** [comment] 2021-03-15 01:44
I've investigated this quite a bit.  I think we should simply remove anything to do with `RememberLoginHash::logout_across_devices` from the session manager module

This line specifically is what's causing the issues:
https://github.com/silverstripe/silverstripe-session-manager/blob/1/src/Security/LogOutAuthenticationHandler.php#L44

I don't think that "logout across devices" has anything to do with "revoke an individual session", so I see no reason why it should be implemented (badly) in this module.

'logout across devices' is already implemented in framework

So my recommendation is we remove all references to `logout_across_devices` within the session-manager module

**Comment by maxime-rainville** [comment] 2021-04-08 21:40
The eagle has landed.

**Closed as completed by maxime-rainville** 2021-04-08 21:40 UTC
